version: '3.8'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    environment:
      - NODE_ENV=development

  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    depends_on:
      - relay

  relay:
    build: ./relay
    ports:
      - "8082:8082"
    environment:
      - RTSP_URL=rtsp://admin:1q2w3e4r@172.16.222.44:554
